config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  resources :users
  resources :interests, only:[:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interest.rb
class Interest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :interests
  has_many :to_interests, through: :interests, source: :user_id


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def new
    @interest = Interest.new
    @user = User.find(params[:user_id])
  end

  def create
    @interest  = Interest.create(interests_params)
    UserMailer.send_email(@interest).deliver
    redirect_back(fallback_location: root_path)
  end

  private
  def interests_params
    params.require(:interest).permit(:name, :email, :phonenumber, :content, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    if login(email)
      flash[:success] = "ログインに成功しました。"
      redirect_to root_path
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
  end

  private
  def login(email)
    @user  = User.find_by(email: email)
    session[:user_id] = @user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update,:destroy]
  def index
    @user = User.new
    @users = User.all
  end

  def show
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.send_signup_email(@user).deliver
      flash[:success] = "メールが送られるのでメール内のurlをクリックして認証をしてください。"
      redirect_to root_path
    else
      render "index"
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_path
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :user_type, :title, :content)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 # 現在ログイン中のユーザーを返す (いる場合)
 def current_user
   if session[:user_id]
     @current_user ||= User.find_by(id: session[:user_id])
   end
 end

 # ユーザーがログインしていればtrue、その他ならfalseを返す
 def logged_in?
   !current_user.nil?
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/User_notifier/send_signup_email.html.slim
<!DOCTYPE html>
html
  head
    meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
  body
    h1 ご登録ありがとうございます。= @user.name さん!
    p
      |
        ご参加いただきありがとうございます。素晴らしい一日を！
        今すぐサインインしてください。

app/views/interests/new.html.slim
= form_for(@interest) do |f|
  = f.hidden_field :user_id, :value=> @user.id
  .form-group
    = f.label :email, 'メールアドレス(非公開)'
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :phonenumber, "電話番号"
    = f.text_field :phonenumber, class: "form-control"
  .form-group
    = f.label :content, 'PRポイント120文字以上400文字以内'
    = f.text_area :content, class: 'form-control'

    = f.submit '送信', class: 'btn btn-success'

app/views/layouts/_error_messages.html.slim
- if model.errors.any?
  .alert alert-warning
    ul
      - model.errors.full_messages.each do |message|
        li = message
  

app/views/layouts/_flash_messages.html.slim
- flash.each do |message_type, message|
  .alert alert- = message_type = message

app/views/layouts/_navbar.html.slim
.container
  .row
   .col-md-12
     #enjoy-matching
      img src="/images/enjoy-matching.jpg"

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title Enjoymatching
    = csrf_meta_tags
    = csp_meta_tag

    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"


  body
    == render 'layouts/navbar'
    .container
      == render 'layouts/flash_messages'

      == yield

      == render 'layouts/footer'

app/views/users/_form.html.slim
= form_for(user) do |f|
  .form-group
    = f.label :email, 'メールアドレス(非公開)'
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
      = f.label :user_type, "生徒"
      = f.radio_button :user_type, 1
      = f.label :user_type, "先生"
      = f.radio_button :user_type, 2
  .form-group
    = f.label :title, 'タイトル'
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content, 'PRポイント120文字以上400文字以内'
    = f.text_area :content, class: 'form-control'


    = f.submit '送信', class: 'btn btn-success'

app/views/users/_users.html.slim
- if users.any?
  - users.each do |user|
    hr
    = user.name
    - if user.user_type == 1
      p 生徒
    - elsif user.user_type == 2
      p 先生
    = user.title
      br
    = user.content
      br
    = link_to "興味ある", new_interest_path(:user_id => user.id)
  - if logged_in?
    = link_to "編集", edit_user_path(current_user)
    = link_to "削除", user_path(current_user), :method => :delete, data: {confirm: "削除しますか？"}
  - else
    p ログイン確認中

app/views/users/edit.html.slim
.row
 .col-md-10
   == render "users/form", user: @user

app/views/users/index.html.slim
.row
 .col-md-10
       h3 募集フォーム
       == render "users/form", user: @user

       == render "users/users", users: @users